//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./hello_types');
//HELPER FUNCTIONS AND STRUCTURES

HelleMethod_sayHello_args = function(args) {
  this.helloMsg = null;
  if (args) {
    if (args.helloMsg !== undefined && args.helloMsg !== null) {
      this.helloMsg = new ttypes.HelloMsg(args.helloMsg);
    }
  }
};
HelleMethod_sayHello_args.prototype = {};
HelleMethod_sayHello_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.helloMsg = new ttypes.HelloMsg();
        this.helloMsg.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelleMethod_sayHello_args.prototype.write = function(output) {
  output.writeStructBegin('HelleMethod_sayHello_args');
  if (this.helloMsg !== null && this.helloMsg !== undefined) {
    output.writeFieldBegin('helloMsg', Thrift.Type.STRUCT, 1);
    this.helloMsg.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HelleMethod_sayHello_result = function(args) {
};
HelleMethod_sayHello_result.prototype = {};
HelleMethod_sayHello_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

HelleMethod_sayHello_result.prototype.write = function(output) {
  output.writeStructBegin('HelleMethod_sayHello_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HelleMethodClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
HelleMethodClient.prototype = {};
HelleMethodClient.prototype.seqid = function() { return this._seqid; }
HelleMethodClient.prototype.new_seqid = function() { return this._seqid += 1; }
HelleMethodClient.prototype.sayHello = function(helloMsg, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_sayHello(helloMsg);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_sayHello(helloMsg);
  }
};

HelleMethodClient.prototype.send_sayHello = function(helloMsg) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('sayHello', Thrift.MessageType.CALL, this.seqid());
  var args = new HelleMethod_sayHello_args();
  args.helloMsg = helloMsg;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HelleMethodClient.prototype.recv_sayHello = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new HelleMethod_sayHello_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
HelleMethodProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
HelleMethodProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

HelleMethodProcessor.prototype.process_sayHello = function(seqid, input, output) {
  var args = new HelleMethod_sayHello_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.sayHello.length === 1) {
    Q.fcall(this._handler.sayHello, args.helloMsg)
      .then(function(result) {
        var result = new HelleMethod_sayHello_result({success: result});
        output.writeMessageBegin("sayHello", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("sayHello", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.sayHello(args.helloMsg, function (err, result) {
      if (err == null) {
        var result = new HelleMethod_sayHello_result((err != null ? err : {success: result}));
        output.writeMessageBegin("sayHello", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("sayHello", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

